### ISSUE TITLE
Unable to create an account

### ISSUE THREAD

**Issue by dasph** [Gabryjiel/UploadSystemPRO#11]
I've hooked up a fresh postgresql database to my local server, ran `php artisan migrate`.
Everything seemed be nice (database had all the required tables). When trying to log in with random credentials - I would get `401 (Unauthorized)` (duuuh...).
Problems appear when trying to create an account. Server replies with `500` ([production version](https://uploadsystempro.herokuapp.com/) possibly faces the same problem).

small preview of the problem:
![image](https://user-images.githubusercontent.com/8137764/103927075-7a729680-5122-11eb-9fa2-503398038f3c.png)

**Comment by dasph** [comment]
It fixed the issue on my machine. I think that the live version possibly has some issues  with the database.
Right now it always responds with `index.html`:
```
C:\Users\dasph>curl https://uploadsystempro.herokuapp.com/api/register -H "Content-Type: application/json"
-d '{\"name":\"ssd\", \"email\":\"sfsdfs@gmail.com\",\"password\":\"aaaa\",\"password_confirmation\":\"aaaa\"}"
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1">
    <meta name="theme-color" content="#f5f5f5">
    <title>Upload System PRO</title>
    <link rel="stylesheet" href="styles/loader.a1ed872e.css">
    <link rel="stylesheet" href="styles/tailwind.9fbcb616.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500&display=swap">
    <link rel="icon" type="image/png" href="favicon.f01a234d.png">
    <script defer="defer" src="bundle.79ea2ec3.js"></script>
</head>
<body>
    <div class="app">
        <div class="loader"><div></div><div></div><div></div><div></div></div>
    </div>
</body>
</html>
```

**Comment by Gabryjiel** [comment]
I don't think it's problem with database because I was able to run migrations on production. I think it's some king of a problem with deployment environment. Maybe wrong entries in config variables (.env).

For now (2 weeks) I wouldn't focus so much on production.
